import Head from "next/head";



interface MyHeadProps {
  page : string | undefined
}

const MyHead = (props:MyHeadProps) => {

  const title = props.page === undefined ? "Filip Niedzielski" : `${props.page} | Filip Niedzielski`

  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default MyHead